steps:
  ###########################################################
  # Create BigQuery Datasets and set IAM policies
  ###########################################################
  - id: 'tf apply'
    name: 'hashicorp/terraform:latest'
    entrypoint: 'sh'
    args:
      - run_terraform.sh
    env:
      - PROJECT_ID=${PROJECT_ID}
      - BQ_LOCATION=${_BQ_LOCATION}
      - BQ_DATASET_ID=${_BQ_DATASET_ID} || 'example_dataset'
      - BRANCH_NAME=${BRANCH_NAME}
      - SHORT_SHA=${SHORT_SHA}
      - _PR_NUMBER=${_PR_NUMBER}
  ###########################################################
  # Build and deploy BigQuery SQL objects
  ###########################################################
  - id: 'dataform run'
    name: dataformco/dataform
    entrypoint: bash
    args:
      - run_dataform.sh
    env:
      - PROJECT_ID=${PROJECT_ID}
      - BQ_LOCATION=${_BQ_LOCATION}
      - BRANCH_NAME=${BRANCH_NAME}
      - SHORT_SHA=${SHORT_SHA}
      - _PR_NUMBER=${_PR_NUMBER}
      - DATAFORM_ACTIONS=${_DATAFORM_ACTIONS}
      - DATAFORM_TAGS=${_DATAFORM_TAGS}
